# Generated by Django 2.2.2 on 2019-06-15 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skill_learn', '0002_text_identifier'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserRatings',
            new_name='UserRating',
        ),
        migrations.AddField(
            model_name='question',
            name='rating',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='topic',
            name='rating',
            field=models.IntegerField(default=0),
        ),
    ]
