# Generated by Django 2.2.2 on 2019-06-15 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skill_learn', '0003_auto_20190615_0605'),
    ]

    operations = [
        migrations.AddField(
            model_name='text',
            name='rating',
            field=models.IntegerField(default=0),
        ),
    ]
